spring.application.name=literalura

# DataSource
spring.datasource.driverClassName=${POSTGRES_DATABASE_DRIVER_CLASS}
spring.datasource.url=${POSTGRES_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_DATASOURCE_USERNAME}
spring.datasource.password=${POSTGRES_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true